=== johnstamps2020/documentation-portal/frontend/page-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://docs.guidewire.com/page.schema.json",
  "title": "Page config",
  "description": "A config for pages",
  "type": "object",
  "additionalProperties": false,
  "required": ["title", "template", "class", "items"],
  "properties": {
    "$schema": {
      "description": "A link to the JSON schema",
      "type": "string"
    },
    "title": {
      "description": "Title of the page",
      "type": "string",
      "examples": [
        "Cortina Documentation",
        "BillingCenter for Guidewire Cloud 2020.11",
        "Self-managed"
      ]
    },
    "template": {
      "description": "Filename of the template in the templates directory that is used to build the page",
      "pattern": "^[^.]+$",
      "examples": ["page", "redirect"]
    },
    "includeInBreadcrumbs": {
      "description": "If set to false, the page is not included in the list of breadcrumbs for descendant pages",
      "type": "boolean"
    },
    "class": {
      "$ref": "#/definitions/class"
    },
    "selector": {
      "description": "A set of links to display in a dropdown on the page",
      "type": "object",
      "examples": [
        {
          "label": "Select release",
          "class": "releaseSelector",
          "selectedItem": "Cortina",
          "items": [
            {
              "label": "Banff",
              "page": "../banff"
            },
            {
              "label": "Aspen",
              "page": "../aspen"
            }
          ]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "selectedItem": {
          "type": "string",
          "description": "Item representing the current page. This item is selected in the dropdown."
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "search_filters": {
      "description": "A set of filters for narrowing down search results",
      "type": "object",
      "examples": [
        {
          "product": [
            "CustomerEngage Account Management",
            "CustomerEngage Account Management for ClaimCenter",
            "CustomerEngage Quote and Buy",
            "ProducerEngage",
            "ProducerEngage for ClaimCenter",
            "ServiceRepEngage",
            "VendorEngage"
          ],
          "platform": ["Cloud"],
          "version": ["2021.04"]
        },
        {
          "product": [
            "BillingCenter",
            "ClaimCenter",
            "Glossary",
            "PolicyCenter",
            "REST API Client"
          ],
          "platform": ["Cloud", "Self-managed"],
          "version": ["2021.04", "latest"]
        }
      ]
    },
    "items": {
      "$ref": "#/definitions/items"
    }
  },
  "definitions": {
    "label": {
      "description": "Text to display on the page",
      "type": "string",
      "examples": [
        "Core Release Notes",
        "InsuranceSuite Configuration Upgrade Tools",
        "PolicyCenter Cloud",
        "Select release"
      ]
    },
    "items": {
      "description": "List of child objects. An object can point to a page, a document or an external link",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "item": {
      "description": "An object that points to a page, a document or an external link",
      "type": "object",
      "required": ["label"],
      "oneOf": [
        {
          "required": ["id"]
        },
        {
          "required": ["page"]
        },
        {
          "required": ["link"]
        },
        {
          "required": ["items"]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "id": {
          "description": "Document ID from the doc site configuration file",
          "pattern": "^[^./].*",
          "examples": [
            "pc1011",
            "restapidraft",
            "guidewirecloudconsoleguideinsurerdevdraft"
          ]
        },
        "page": {
          "description": "Path to a page directory",
          "type": "string",
          "examples": [
            "billingCenterCloud",
            "../../jutro/4.1.1",
            "guidewireCloudPlatform"
          ]
        },
        "link": {
          "description": "External link",
          "type": "string",
          "examples": [
            "./de-DE/cc/1003/ApplicationGuide.pdf",
            "https://docs.guidewire.com/support",
            "../../InstallationGuide.html"
          ]
        },
        "env": {
          "description": "List of environments for which the object is generated",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["dev", "int", "staging", "prod"]
          },
          "examples": [["dev", "staging", "prod"], ["int"]]
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "class": {
      "description": "Name of the CSS selector that is applied to the main page element. /server/public/stylesheets/main.css.",
      "type": "string",
      "examples": [
        "threeCards",
        "twoColumns",
        "categoryCard cardShadow",
        "banff threeCards",
        "aspen threeCards"
      ]
    }
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/cortina/infocenter/index.json
{
  "title": "DataHub",
  "template": "page.j2",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "iccloudrncortina"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Product Guide",
          "id": "iccloudproductcortina"
        },
        {
          "label": "BI Applications",
          "id": "iccloudbiappcortina"
        },
        {
          "label": "Reports",
          "id": "iccloudreportscortina"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Installation",
          "id": "iccloudinstallcortina"
        },
        {
          "label": "Upgrade",
          "id": "iccloudupgradecortina"
        }
      ]
    },
    {
      "label": "Configuration",
      "class": "subject configuration",
      "items": [
        {
          "label": "Configuration",
          "id": "iccloudconfigcortina"
        },
        {
          "label": "Data Specifications",
          "id": "icclouddataspeccortina"
        }
      ]
    },
    {
      "label": "Administration",
      "class": "subject administration",
      "items": [
        {
          "label": "Administration",
          "id": "iccloudadmincortina"
        }
      ]
    },
    {
      "label": "Development",
      "class": "subject development",
      "items": [
        {
          "label": "Developer Reference",
          "id": "icclouddevrefcortina"
        }
      ]
    },
    {
      "label": "Glossary",
      "class": "subject glossary",
      "items": [
        {
          "label": "Glossary",
          "id": "is202011glossary"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/localizedDocs/fr-FR/pc/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "PolicyCenter",
  "template": "page.j2",
  "class": "threeCards version fr-FR l10n",
  "selector": {
    "label": "Choisissez un produit",
    "selectedItem": "PolicyCenter",
    "items": [
      {
        "label": "BillingCenter",
        "page": "../bc"
      },
      {
        "label": "ClaimCenter",
        "page": "../cc"
      }
    ]
  },
  "items": [
    {
      "label": "2020.05",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guide de l'application",
          "link": "/fr-FR/pc/2020.05/ISCL_202005_fr_PC-AppGuide.pdf"
        },
        {
          "label": "Guide des personnes-ressources de Guidewire",
          "link": "/fr-FR/pc/2020.05/ISCL_202005_fr_PC_ContactMgmtGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.2",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guide de configuration",
          "link": "/fr-FR/pc/10.0.2/ConfigGuide.pdf"
        },
        {
          "label": "Guide des personnes-ressources de Guidewire",
          "link": "/fr-FR/pc/10.0.2/ContactMgmtGuide.pdf"
        },
        {
          "label": "Guide d'installation",
          "link": "/fr-FR/pc/10.0.2/InstallGuide.pdf"
        },
        {
          "label": "Guide de l'application",
          "link": "/fr-FR/pc/10.0.2/PC-AppGuide.pdf"
        },
        {
          "label": "Guide des règles",
          "link": "/fr-FR/pc/10.0.2/RulesGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.0",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guide de l'application",
          "link": "/fr-FR/pc/10.0.0/fr-PC-AppGuide.pdf"
        },
        {
          "label": "Guide de configuration",
          "link": "/fr-FR/pc/10.0.0/fr-PC-ConfigGuide.pdf"
        },
        {
          "label": "Guide de gestion des contacts",
          "link": "/fr-FR/pc/10.0.0/fr-PC-ContactMgmtGuide.pdf"
        },
        {
          "label": "Guide d'installation",
          "link": "/fr-FR/pc/10.0.0/fr-PC-InstallGuide.pdf"
        },
        {
          "label": "Guide des règles",
          "link": "/fr-FR/pc/10.0.0/fr-PC-RulesGuide.pdf"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/elysian/producerEngage/2022.05/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "ProducerEngage 2022.05",
  "template": "page",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "dx202205perelnotes"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Installation Guide",
          "id": "dx202205peinstall"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Application Guide",
          "id": "dx202205peapp"
        }
      ]
    },
    {
      "label": "Development",
      "class": "subject development",
      "items": [
        {
          "label": "Developer's Guide",
          "id": "dx202205pedev"
        },
        {
          "label": "Digital Services Reference Guides",
          "id": "dx202205perefguides"
        },
        {
          "label": "Digital Frontend API Documentation",
          "id": "dxjsdocs202205"
        }
      ]
    }
  ],
  "search_filters": {
    "platform": [
      "Cloud"
    ],
    "language": ["en"]
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/developerResources/dobson/index.json
{
  "$schema": "../../../page-schema.json",
  "title": "Developer Resources",
  "template": "page",
  "class": "blue-theme dobson threeCards",
  "selector": {
    "label": "Select release",
    "selectedItem": "Dobson",
    "items": [
      {
        "label": "Cortina",
        "page": "../cortina"
      },
      {
        "label": "Banff",
        "page": "../banff"
      }
    ]
  },
  "items": [
    {
      "label": "InsuranceNow API reference",
      "class": "productFamily cardShadow",
      "id": "in20212apiref"
    },
    {
      "label": "ClaimCenter API reference",
      "class": "productFamily cardShadow",
      "id": "ccapirefdobson"
    },
    {
      "label": "PolicyCenter API reference",
      "class": "productFamily cardShadow",
      "id": "pcapirefdobson"
    },
    {
      "label": "APD API reference",
      "class": "productFamily cardShadow",
      "id": "pcapirefdobson",
      "env": ["int"]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/globalContent/ipa/2.0/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "InsuranceSuite Package for Australia for Guidewire Cloud 2.0",
  "template": "page",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "ipacloudelysianrn"
        }
      ]
    },
    {
      "label": "Developers",
      "class": "subject development",
      "items": [
        {
          "label": "Configuration Guide",
          "id": "ipacloudelysianconfig"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Australia Personal Motor Policy",
          "id": "ipacloudelysianapmp"
        },
        {
          "label": "Australia Personal Motor Claims",
          "id": "ipacloudelysianapmc"
        },
        {
          "label": "GST for Claims",
          "id": "ipacloudelysiangstc"
        },
        {
          "label": "Address Lookup",
          "id": "ipacloudelysianal"
        },
        {
          "label": "Vehicle Lookup",
          "id": "ipacloudelysianvl"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/es-ES/bc/index.json
{
  "title": "BillingCenter",
  "template": "page.j2",
  "class": "threeCards",
  "items": [
    {
      "label": "2022.05",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guía de la aplicación",
          "link": "/es-ES/bc/2022.05/BC-AppGuide_es-ES.pdf"
        },
        {
          "label": "Guía de configuración",
          "link": "/es-ES/bc/2022.05/BC-ConfigGuide_es-ES.pdf"
        }
      ]
    },
    {
      "label": "2021.11",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guía de configuración y flujos de negocio de la API de la nube",
          "link": "/es-ES/bc/2021.11/BC v.2021.11 es-ES CloudAPIGuide-BusinessFlows.pdf"
        }
      ]
    },
    {
      "label": "10.1.1",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guía de configuración",
          "link": "/es-ES/bc/10.1.1/BC1011_es-ES_ConfigGuide.pdf"
        },
        {
          "label": "Guía de instalación",
          "link": "/es-ES/bc/10.1.1/BC1011_es-ES_InstallGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.2",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guía de aplicaciones",
          "link": "/es-ES/bc/10.0.2/esES-BC-AppGuide.pdf"
        },
        {
          "label": "Guía de gestión de contactos de Guidewire",
          "link": "/es-ES/bc/10.0.2/esES-BC-ContactMgmtGuide.pdf"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/de-DE/dh/index.json
{
  "title": "DataHub",
  "template": "page",
  "class": "threeCards",
  "items": [
    {
      "label": "10.0.0",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Administrationshandbuch",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-admin-de.pdf"
        },
        {
          "label": "DataHub Konfigurationshandbuch",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-config-de.pdf"
        },
        {
          "label": "Leitfaden zur Datenspezifikation",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-dataspec-de.pdf"
        },
        {
          "label": "Installationshandbuch",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-install-de.pdf"
        },
        {
          "label": "Berichtshandbuch",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-reports-de.pdf"
        },
        {
          "label": "Upgrade-Handbuch",
          "link": "/l10n/de-DE/dh/10.0.0/DH10-upgrade-de.pdf"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/es-ES/ce-claims/index.json
{
  "title": "CustomerEngage Account Management for ClaimCenter",
  "template": "page",
  "class": "threeCards",
  "items": [
    {
      "label": "2022.05",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guía de la aplicación",
          "link": "/l10n/es-ES/ce-claims/2022.05/es-ES v.2022.05 CE-AM Claims_AppGuide.pdf"
        }
      ]
    }
  ]
}
