=== johnstamps2020/documentation-portal/frontend/page-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://docs.guidewire.com/page.schema.json",
  "title": "Page config",
  "description": "A config for pages",
  "type": "object",
  "additionalProperties": false,
  "required": ["title", "template", "class", "items"],
  "properties": {
    "$schema": {
      "description": "A link to the JSON schema",
      "type": "string"
    },
    "title": {
      "description": "Title of the page",
      "type": "string",
      "examples": [
        "Cortina Documentation",
        "BillingCenter for Guidewire Cloud 2020.11",
        "Self-managed"
      ]
    },
    "template": {
      "description": "Filename of the template in the templates directory that is used to build the page",
      "pattern": "^[^.]+$",
      "examples": ["page", "redirect"]
    },
    "includeInBreadcrumbs": {
      "description": "If set to false, the page is not included in the list of breadcrumbs for descendant pages",
      "type": "boolean"
    },
    "class": {
      "$ref": "#/definitions/class"
    },
    "selector": {
      "description": "A set of links to display in a dropdown on the page",
      "type": "object",
      "examples": [
        {
          "label": "Select release",
          "class": "releaseSelector",
          "selectedItem": "Cortina",
          "items": [
            {
              "label": "Banff",
              "page": "../banff"
            },
            {
              "label": "Aspen",
              "page": "../aspen"
            }
          ]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "selectedItem": {
          "type": "string",
          "description": "Item representing the current page. This item is selected in the dropdown."
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "search_filters": {
      "description": "A set of filters for narrowing down search results",
      "type": "object",
      "examples": [
        {
          "product": [
            "CustomerEngage Account Management",
            "CustomerEngage Account Management for ClaimCenter",
            "CustomerEngage Quote and Buy",
            "ProducerEngage",
            "ProducerEngage for ClaimCenter",
            "ServiceRepEngage",
            "VendorEngage"
          ],
          "platform": ["Cloud"],
          "version": ["2021.04"]
        },
        {
          "product": [
            "BillingCenter",
            "ClaimCenter",
            "Glossary",
            "PolicyCenter",
            "REST API Client"
          ],
          "platform": ["Cloud", "Self-managed"],
          "version": ["2021.04", "latest"]
        }
      ]
    },
    "items": {
      "$ref": "#/definitions/items"
    }
  },
  "definitions": {
    "label": {
      "description": "Text to display on the page",
      "type": "string",
      "examples": [
        "Core Release Notes",
        "InsuranceSuite Configuration Upgrade Tools",
        "PolicyCenter Cloud",
        "Select release"
      ]
    },
    "items": {
      "description": "List of child objects. An object can point to a page, a document or an external link",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "item": {
      "description": "An object that points to a page, a document or an external link",
      "type": "object",
      "required": ["label"],
      "oneOf": [
        {
          "required": ["id"]
        },
        {
          "required": ["page"]
        },
        {
          "required": ["link"]
        },
        {
          "required": ["items"]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "id": {
          "description": "Document ID from the doc site configuration file",
          "pattern": "^[^./].*",
          "examples": [
            "pc1011",
            "restapidraft",
            "guidewirecloudconsoleguideinsurerdevdraft"
          ]
        },
        "page": {
          "description": "Path to a page directory",
          "type": "string",
          "examples": [
            "billingCenterCloud",
            "../../jutro/4.1.1",
            "guidewireCloudPlatform"
          ]
        },
        "link": {
          "description": "External link",
          "type": "string",
          "examples": [
            "./de-DE/cc/1003/ApplicationGuide.pdf",
            "https://docs.guidewire.com/support",
            "../../InstallationGuide.html"
          ]
        },
        "env": {
          "description": "List of environments for which the object is generated",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["dev", "int", "staging", "prod"]
          },
          "examples": [["dev", "staging", "prod"], ["int"]]
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "class": {
      "description": "Name of the CSS selector that is applied to the main page element. /server/public/stylesheets/main.css.",
      "type": "string",
      "examples": [
        "threeCards",
        "twoColumns",
        "categoryCard cardShadow",
        "banff threeCards",
        "aspen threeCards"
      ]
    }
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/dobson/pcGwCloud/2021.11/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "PolicyCenter for Guidewire Cloud 2021.11",
  "template": "page",
  "class": "twoColumns",
  "selector": {
    "label": "Select release",
    "selectedItem": "Dobson (2021.11)",
    "items": [
      {
        "label": "Flaine (2022.09)",
        "page": "../../../flaine/pcGwCloud/2022.09"
      },
      {
        "label": "Elysian (2022.05)",
        "page": "../../../elysian/pcGwCloud/2022.05"
      },
      {
        "label": "Cortina (2021.04)",
        "page": "../../../cortina/policyCenterCloud/pcGwCloud/2021.04"
      },
      {
        "label": "Banff (2020.11)",
        "page": "../../../banff/policyCenterCloud/pcGwCloud/2020.11"
      },
      {
        "label": "Aspen (2020.05)",
        "page": "../../../aspen/policyCenterCloud"
      }
    ]
  },
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "ispc202111releasenotes"
        },
        {
          "label": "New and Changed",
          "id": "ispc202111newandchanged"
        },
        {
          "label": "Guidewire Testing Framework Release Notes",
          "id": "testingframeworksrndobson"
        },
        {
          "label": "InsuranceSuite Configuration Upgrade Tools",
          "id": "isconfigupgradetools450"
        },
        {
          "label": "InsuranceSuite Configuration Upgrade Tools Compatibility",
          "id": "isupgradecompatibility"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Developer Setup",
          "id": "ispc202111devsetup"
        },
        {
          "label": "Upgrade",
          "id": "ispc202111upgrade"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Application Guide",
          "id": "ispc202111app"
        },
        {
          "label": "Contact Management",
          "id": "is202111contact"
        }
      ]
    },
    {
      "label": "Administration",
      "class": "subject administration",
      "items": [
        {
          "label": "Administration",
          "id": "ispc202111admin"
        },
        {
          "label": "Data Archiving",
          "id": "ispc202111dataarchiving"
        }
      ]
    },
    {
      "label": "Configuration",
      "class": "subject configuration",
      "items": [
        {
          "label": "Advanced Product Designer in PolicyCenter",
          "id": "ispc202111apd"
        },
        {
          "label": "Configuration",
          "id": "ispc202111config"
        },
        {
          "label": "Globalization",
          "id": "ispc202111global"
        },
        {
          "label": "Gosu Rules",
          "id": "ispc202111rules"
        },
        {
          "label": "Product Designer",
          "id": "ispc202111pd"
        },
        {
          "label": "Product Model",
          "id": "ispc202111pm"
        }
      ]
    },
    {
      "label": "Integration",
      "class": "subject integration",
      "items": [
        {
          "label": "Overview of Cloud Integration",
          "id": "is202111integoverview"
        },
        {
          "label": "Cloud API Authentication",
          "id": "ispc202111apica"
        },
        {
          "label": "Cloud API Business Flows and Configuration",
          "id": "ispc202111apibf"
        },
        {
          "label": "Cloud API ContactManager",
          "id": "ispc202111apicm"
        },
        {
          "label": "Cloud API Reference",
          "id": "pcapirefdobson"
        },
        {
          "label": "Plugins, Prebuilt Integrations, and SOAP APIs",
          "id": "ispc202111integ"
        },
        {
          "label": "REST API Framework",
          "id": "ispc202111restapifw"
        },
        {
          "label": "REST API Client",
          "id": "isrestapiclientguide"
        }
      ]
    },
    {
      "label": "Development",
      "class": "subject development",
      "items": [
        {
          "label": "Gosu Reference",
          "id": "gosureflatest"
        },
        {
          "label": "GUnit Testing",
          "id": "ispc202111testing"
        },
        {
          "label": "API Testing (GT: API)",
          "id": "testingframeworksapidobson"
        },
        {
          "label": "User Interface Testing (GT: UI)",
          "id": "testingframeworksuidobson"
        }
      ]
    },
    {
      "label": "Glossary",
      "class": "subject glossary",
      "items": [
        {
          "label": "Glossary",
          "id": "gwglossary"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/flaine/featurePreview/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "Feature Preview - Early Access Documentation",
  "template": "page",
  "class": "twoColumns featurePreview",
  "items": [
    {
      "label": "Jutro",
      "class": "subject development",
      "items": [
        {
          "label": "Jutro Digital Platform",
          "id": "jutroplatformnext"
        },
        {
          "label": "Jutro SDK",
          "id": "jutrosdknext"
        }
      ]
    },
    {
      "label": "Rules",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Guidewire Rules Release Notes",
          "id": "gwrulesrn"
        },
        {
          "label": "Guidewire Rules",
          "id": "gwrules"
        }
      ]
    },
    {
      "label": "Integration Framework",
      "class": "subject development",
      "items": [
        {
          "label": "App Events Release Notes",
          "id": "appeventsrn"
        },
        {
          "label": "App Events for Developers",
          "id": "appeventsdev"
        },
        {
          "label": "Webhooks API Reference",
          "id": "webhooksapinext"
        }
      ]
    },
    {
      "label": "Testing",
      "class": "subject bestPractices",
      "items": [
        {
          "label": "Data Masking",
          "id": "datamasking"
        },
        {
          "label": "Load and Performance Testing",
          "id": "testingframeworksloadflaine"
        },
        {
          "label": "User Interface Accessibility Testing",
          "id": "is202209access"
        }
      ]
    },
    {
      "label": "Rating",
      "class": "subject configuration",
      "items": [
        {
          "label": "Cloud Rating",
          "id": "cloudratingdraft"
        }
      ]
    },
    {
      "label": "Data",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Data Studio",
          "id": "datastudiorelease"
        },
        {
          "label": "Data Studio",
          "id": "datastudiodraft"
        }
      ]
    },
    {
      "label": "Advanced Product Designer for Claims",
      "class": "subject development",
      "items": [
        {
          "label": "APD for Claims Guide",
          "id": "apdclaims"
        }
      ]
    },
    {
      "label": "Cloud Console",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Cloud Console Root Doc Early Access",
          "id": "guidewirecloudconsolerootearlyaccess"
        }
      ]
    },
    {
      "label": "Configuration",
      "class": "subject configuration",
      "items": [
        {
          "label": "Experience Manager",
          "id": "experiencemgrdraft"
        },
        {
          "label": "String Manager",
          "id": "stringmanagerpcdraft"
        },
        {
          "label": "Workset Manager",
          "id": "worksetmgr"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/flaine/global-ref-apps/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "Global Content Reference Applications",
  "template": "page",
  "class": "blue-theme flaine threeCards",
  "items": [
    {
      "label": "London Market",
      "class": "categoryCard cardShadow",
      "page": "../../../globalContent/iplm/flaine"
    },
    {
      "label": "UK Market",
      "class": "categoryCard cardShadow",
      "page": "../../../globalContent/ipuk/1.1"
    },
    {
      "label": "US Standards-based Template Framework",
      "class": "categoryCard cardShadow",
      "page": "../../../globalContent/sbt"
    }
  ],
  "search_filters": {
    "platform": [
      "Cloud"
    ]
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n/ja-JP/pc/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "PolicyCenter",
  "template": "page",
  "class": "threeCards version ja-JP l10n",
  "items": [
    {
      "label": "Gosu リファレンスガイド",
      "class": "categoryCard cardShadow",
      "id": "gosureflatestjaJP"
    },
    {
      "label": "Integration Gateway",
      "class": "categoryCard cardShadow",
      "id": "integgatewaydevlatestjaJP"
    },
    {
      "label": "2021.04 Cortina",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "ルールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2021.04 Cortina/PC_CL202104_ja-JP_RulesGuide.pdf"
        },
        {
          "label": "テストガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2021.04 Cortina/PC_CL202104_ja-JP_TestingGuide.pdf"
        }
      ]
    },
    {
      "label": "2020.11 Banff",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "インストールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2020.11 Banff/PCCloud202011_ja-JP_InstallGuide.pdf"
        },
        {
          "label": "Advanced Product Designer ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2020.11 Banff/Cloud202011_ja-JP_AdvancedProductDesigner.pdf"
        },
        {
          "label": "コンフィギュレーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2020.11 Banff/PCCloud202011_ja-JP_ConfigGuide.pdf"
        }
      ]
    },
    {
      "label": "2020.05 Aspen",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guidewire 連絡先管理ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2020.05 Aspen/IS_CL202005-PC-ContactMgmtGuide-ja_JP.pdf"
        },
        {
          "label": "アプリケーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/2020.05 Aspen/IS_CL202005-PC-AppGuide-ja_JP.pdf"
        }
      ]
    },
    {
      "label": "10.1.1",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "インストールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.1.1/PC1011_ja-JP_InstallGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.2",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "インストールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-InstallGuide.pdf"
        },
        {
          "label": "ルールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-RulesGuide.pdf"
        },
        {
          "label": "保険商品モデルガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-ProductModelGuide.pdf"
        },
        {
          "label": "システム管理ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-AdminGuide.pdf"
        },
        {
          "label": "連携ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-IntegrationGuide.pdf"
        },
        {
          "label": "Gosu リファレンスガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-GosuRefGuide.pdf"
        },
        {
          "label": "Guidewire 連絡先管理ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-ContactMgmtGuide.pdf"
        },
        {
          "label": "PolicyCenter  用語集",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-Glossary.pdf"
        },
        {
          "label": "Product Designer ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-ProductDesignerGuide.pdf"
        },
        {
          "label": "コンフィギュレーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-ConfigGuide.pdf"
        },
        {
          "label": "アプリケーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-AppGuide.pdf"
        },
        {
          "label": "ベストプラクティスガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.2/ja-PC-BestPracticesGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.0",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "インストールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-InstallGuide.pdf"
        },
        {
          "label": "ルールガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-RulesGuide.pdf"
        },
        {
          "label": "保険商品モデルガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-ProductModelGuide.pdf"
        },
        {
          "label": "連携ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-IntegrationGuide.pdf"
        },
        {
          "label": "連絡先管理ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-ContactMgmtGuide.pdf"
        },
        {
          "label": "Product Designer ガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-ProductDesignerGuide.pdf"
        },
        {
          "label": "コンフィギュレーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-ConfigGuide.pdf"
        },
        {
          "label": "アプリケーションガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-AppGuide.pdf"
        },
        {
          "label": "ベストプラクティスガイド",
          "link": "/l10n/pdfs/ja-JP/pc/10.0.0/ja-PC-BestPracticesGuide.pdf"
        }
      ]
    }
  ],
  "selector": {
    "label": "製品を選択",
    "selectedItem": "PolicyCenter",
    "items": [
      {
        "label": "Garmisch (2023.02) の新機能",
        "page": "../202302garmischwhatsnew"
      },
      {
        "label": "BillingCenter",
        "page": "../bc"
      },
      {
        "label": "ClaimCenter",
        "page": "../cc"
      },
      {
        "label": "CustomerEngage Account Management",
        "page": "../ce-am"
      },
      {
        "label": "CustomerEngage Account Management for ClaimCenter",
        "page": "../ce-claims"
      },
      {
        "label": "CustomerEngage Quote and Buy",
        "page": "../ce-qb"
      },
      {
        "label": "InsuranceSuite Contact Management",
        "page": "../cm"
      },
      {
        "label": "Cloud Platform",
        "page": "../cp"
      },
      {
        "label": "Guidewire Testing",
        "page": "../gtest"
      },
      {
        "label": "Guidewire Identity Federation Hub",
        "page": "../gwid"
      },
      {
        "label": "Guidewire for Salesforce",
        "page": "../gwsf"
      },
      {
        "label": "InsuranceSuite Configuration Upgrade Tools",
        "page": "../is-configupgradetools"
      },
      {
        "label": "ProducerEngage",
        "page": "../pe"
      },
      {
        "label": "ServiceRepEngage",
        "page": "../sre"
      },
      {
        "label": "VendorEngage",
        "page": "../ve"
      }
    ]
  },
  "search_filters": {
    "language": ["ja"]
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/selfManagedProducts/ipf/latest/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "IRSA Integration for ClaimCenter (version 1.1)",
  "template": "page.j2",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "midipfrndraft"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Overview",
          "id": "midipfoverviewdraft"
        },
        {
          "label": "Adjuster Guide",
          "id": "midipfadjusterdraft"
        }
      ]
    },
    {
      "label": "Administration",
      "class": "subject administration",
      "items": [
        {
          "label": "Administration Guide",
          "id": "midipfadmindraft"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/cortina/policyCenterCloud/pcGwCloud/earlyaccess/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "PolicyCenter for Guidewire Cloud earlyaccess",
  "template": "page.j2",
  "class": "twoColumns",
  "selector": {
    "label": "Select version",
    "selectedItem": "earlyaccess",
    "items": [
      {
        "label": "latest",
        "page": "../latest"
      }
    ]
  },
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "ispccloudeareleasenotes"
        },
        {
          "label": "New and Changed",
          "id": "ispccloudeanewandchanged"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Installation",
          "id": "ispccloudeainstall"
        },
        {
          "label": "Upgrade",
          "id": "ispccloudeaupgrade"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Application Guide",
          "id": "ispccloudeaapp"
        },
        {
          "label": "Contact Management",
          "id": "iscloudeacontact"
        }
      ]
    },
    {
      "label": "Administration",
      "class": "subject administration",
      "items": [
        {
          "label": "Administration",
          "id": "ispccloudeaadmin"
        }
      ]
    },
    {
      "label": "Best Practices",
      "class": "subject bestPractices",
      "items": [
        {
          "label": "Best practices",
          "id": "ispccloudeabestpractice"
        }
      ]
    },
    {
      "label": "Configuration",
      "class": "subject configuration",
      "items": [
        {
          "label": "Advanced Product Designer",
          "id": "ispccloudeaapd"
        },
        {
          "label": "Configuration",
          "id": "ispccloudeaconfig"
        },
        {
          "label": "Globalization",
          "id": "ispccloudeaglobal"
        },
        {
          "label": "Rules",
          "id": "ispccloudearules"
        },
        {
          "label": "Product Designer",
          "id": "ispccloudeapd"
        },
        {
          "label": "Product Model",
          "id": "ispccloudeapm"
        }
      ]
    },
    {
      "label": "Integration",
      "class": "subject integration",
      "items": [
        {
          "label": "Integration",
          "id": "ispccloudeainteg"
        },
        {
          "label": "Cloud API Developer Guide",
          "id": "ispccloudeacloudapi"
        },
        {
          "label": "REST API Framework",
          "id": "ispccloudearestapifw"
        },
        {
          "label": "REST API Client",
          "id": "iscloudearestapiclient"
        }
      ]
    },
    {
      "label": "Development",
      "class": "subject development",
      "items": [
        {
          "label": "Gosu Reference",
          "id": "ispccloudeagosu"
        },
        {
          "label": "Test Automation Guide",
          "id": "ispccloudeatesting"
        }
      ]
    },
    {
      "label": "Glossary",
      "class": "subject glossary",
      "items": [
        {
          "label": "Glossary",
          "id": "iscloudeaglossary"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/globalContent/ipf/latest/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "ClaimCenter Package for France",
  "template": "page",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "midipfcloudrn"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Overview",
          "id": "midipfcloudoverview"
        },
        {
          "label": "Adjuster Guide",
          "id": "midipfcloudadjuster"
        }
      ]
    },
    {
      "label": "Administration",
      "class": "subject administration",
      "items": [
        {
          "label": "Administration Guide",
          "id": "midipfcloudadmin"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/globalContent/messageStore/2023.10/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "Global Content - Message Store",
  "template": "page",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "gondolasmsrninnsbruck"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Application Guide",
          "id": "gondolasmsappinnsbruck"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Installation and Deployment",
          "id": "gondolasmsinstallinnsbruck"
        }
      ]
    },
    {
      "label": "Configuration",
      "class": "subject configuration",
      "items": [
        {
          "label": "Configuration",
          "id": "gondolasmsconfiginnsbruck"
        }
      ]
    },
    {
      "label": "Integration",
      "class": "subject integration",
      "items": [
        {
          "label": "Integration",
          "id": "gondolasmsinteginnsbruck"
        }
      ]
    }
  ],
  "search_filters": {
    "language": ["en"]
  }
}
