=== johnstamps2020/documentation-portal/frontend/page-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://docs.guidewire.com/page.schema.json",
  "title": "Page config",
  "description": "A config for pages",
  "type": "object",
  "additionalProperties": false,
  "required": ["title", "template", "class", "items"],
  "properties": {
    "$schema": {
      "description": "A link to the JSON schema",
      "type": "string"
    },
    "title": {
      "description": "Title of the page",
      "type": "string",
      "examples": [
        "Cortina Documentation",
        "BillingCenter for Guidewire Cloud 2020.11",
        "Self-managed"
      ]
    },
    "template": {
      "description": "Filename of the template in the templates directory that is used to build the page",
      "pattern": "^[^.]+$",
      "examples": ["page", "redirect"]
    },
    "includeInBreadcrumbs": {
      "description": "If set to false, the page is not included in the list of breadcrumbs for descendant pages",
      "type": "boolean"
    },
    "class": {
      "$ref": "#/definitions/class"
    },
    "selector": {
      "description": "A set of links to display in a dropdown on the page",
      "type": "object",
      "examples": [
        {
          "label": "Select release",
          "class": "releaseSelector",
          "selectedItem": "Cortina",
          "items": [
            {
              "label": "Banff",
              "page": "../banff"
            },
            {
              "label": "Aspen",
              "page": "../aspen"
            }
          ]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "selectedItem": {
          "type": "string",
          "description": "Item representing the current page. This item is selected in the dropdown."
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "search_filters": {
      "description": "A set of filters for narrowing down search results",
      "type": "object",
      "examples": [
        {
          "product": [
            "CustomerEngage Account Management",
            "CustomerEngage Account Management for ClaimCenter",
            "CustomerEngage Quote and Buy",
            "ProducerEngage",
            "ProducerEngage for ClaimCenter",
            "ServiceRepEngage",
            "VendorEngage"
          ],
          "platform": ["Cloud"],
          "version": ["2021.04"]
        },
        {
          "product": [
            "BillingCenter",
            "ClaimCenter",
            "Glossary",
            "PolicyCenter",
            "REST API Client"
          ],
          "platform": ["Cloud", "Self-managed"],
          "version": ["2021.04", "latest"]
        }
      ]
    },
    "items": {
      "$ref": "#/definitions/items"
    }
  },
  "definitions": {
    "label": {
      "description": "Text to display on the page",
      "type": "string",
      "examples": [
        "Core Release Notes",
        "InsuranceSuite Configuration Upgrade Tools",
        "PolicyCenter Cloud",
        "Select release"
      ]
    },
    "items": {
      "description": "List of child objects. An object can point to a page, a document or an external link",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "item": {
      "description": "An object that points to a page, a document or an external link",
      "type": "object",
      "required": ["label"],
      "oneOf": [
        {
          "required": ["id"]
        },
        {
          "required": ["page"]
        },
        {
          "required": ["link"]
        },
        {
          "required": ["items"]
        }
      ],
      "properties": {
        "label": {
          "$ref": "#/definitions/label"
        },
        "class": {
          "$ref": "#/definitions/class"
        },
        "id": {
          "description": "Document ID from the doc site configuration file",
          "pattern": "^[^./].*",
          "examples": [
            "pc1011",
            "restapidraft",
            "guidewirecloudconsoleguideinsurerdevdraft"
          ]
        },
        "page": {
          "description": "Path to a page directory",
          "type": "string",
          "examples": [
            "billingCenterCloud",
            "../../jutro/4.1.1",
            "guidewireCloudPlatform"
          ]
        },
        "link": {
          "description": "External link",
          "type": "string",
          "examples": [
            "./de-DE/cc/1003/ApplicationGuide.pdf",
            "https://docs.guidewire.com/support",
            "../../InstallationGuide.html"
          ]
        },
        "env": {
          "description": "List of environments for which the object is generated",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["dev", "int", "staging", "prod"]
          },
          "examples": [["dev", "staging", "prod"], ["int"]]
        },
        "items": {
          "$ref": "#/definitions/items"
        }
      }
    },
    "class": {
      "description": "Name of the CSS selector that is applied to the main page element. /server/public/stylesheets/main.css.",
      "type": "string",
      "examples": [
        "threeCards",
        "twoColumns",
        "categoryCard cardShadow",
        "banff threeCards",
        "aspen threeCards"
      ]
    }
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/globalContent/ipg/3.7/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "Global Content - Germany",
  "template": "page",
  "class": "twoColumns",
  "selector": {
    "label": "Select release",
    "selectedItem": "3.7",
    "items": [
      {
        "label": "3.6",
        "page": "../3.6"
      }
    ]
  },
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "midipgrnen37"
        },
        {
          "label": "Release Notes (German)",
          "id": "midipgrnde37"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "Application Guide",
          "id": "midipgapp37"
        },
        {
          "label": "Application Guide (German)",
          "id": "midipgappde37"
        },
        {
          "label": "Implementation",
          "id": "midipgimpl37"
        }
      ]
    },
    {
      "label": "Installation",
      "class": "subject installation",
      "items": [
        {
          "label": "Installation",
          "id": "midipginstall37"
        }
      ]
    },
    {
      "label": "Glossary",
      "class": "subject glossary",
      "items": [
        {
          "label": "Glossary",
          "id": "midipgglossary37"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/it-IT/sre/index.json
{
  "title": "ServiceRepEngage",
  "template": "page",
  "class": "threeCards",
  "items": [
    {
      "label": "2022.05",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guida all'installazione",
          "link": "/l10n/it-IT/sre/2022.05/it-IT Digital v.2022.05 SRE InstallGuide.pdf"
        },
        {
          "label": "Guida all'applicazione",
          "link": "/l10n/it-IT/sre/2022.05/it-IT Digital v.2022.05 SRE_AppGuide.pdf"
        }
      ]
    },
    {
      "label": "11.3",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guida all'installazione",
          "link": "/l10n/it-IT/sre/11.3/it-SRE-IT - 11.3-onprem-InstallGuide.pdf"
        }
      ]
    },
    {
      "label": "10.0.1",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guida all'applicazione",
          "link": "/l10n/it-IT/sre/10.0.1/it-SRE_AppGuide.pdf"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/es-ES/index.json
{
  "title": "Español (España)",
  "template": "page.j2",
  "class": "threeCards",
  "items": [
    {
      "label": "Advanced Product Designer",
      "class": "productFamily cardShadow",
      "page": "apd"
    },
    {
      "label": "BillingCenter",
      "class": "productFamily cardShadow",
      "page": "bc"
    },
    {
      "label": "ClaimCenter",
      "class": "productFamily cardShadow",
      "page": "cc"
    },
    {
      "label": "CustomerEngage Account Management",
      "class": "productFamily cardShadow",
      "page": "ce-am"
    },
    {
      "label": "CustomerEngage Account Management for ClaimCenter",
      "class": "productFamily cardShadow",
      "page": "ce-claims"
    },
    {
      "label": "CustomerEngage Quote and Buy",
      "class": "productFamily cardShadow",
      "page": "ce-qb"
    },
    {
      "label": "IS Contact Manager",
      "class": "productFamily cardShadow",
      "page": "cm"
    },
    {
      "label": "PolicyCenter",
      "class": "productFamily cardShadow",
      "page": "pc"
    },
    {
      "label": "ProducerEngage",
      "class": "productFamily cardShadow",
      "page": "pe"
    },
    {
      "label": "ProducerEngage for ClaimCenter",
      "class": "productFamily cardShadow",
      "page": "pe-claims"
    },
    {
      "label": "ServiceRepEngage",
      "class": "productFamily cardShadow",
      "page": "sre"
    },
    {
      "label": "VendorEngage",
      "class": "productFamily cardShadow",
      "page": "ve"
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n-new/pt-BR/dh/index.json
{
  "title": "DataHub",
  "template": "page.j2",
  "class": "threeCards",
  "items": [
    {
      "label": "10.0.0",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guia de administração",
          "link": "/pt-BR/dh/10.0.0/DH10-admin-pt.pdf"
        },
        {
          "label": "DataHub Guia de configuração",
          "link": "/pt-BR/dh/10.0.0/DH10-config-pt.pdf"
        },
        {
          "label": "Guia de especificações de dados",
          "link": "/pt-BR/dh/10.0.0/DH10-dataspec-pt.pdf"
        },
        {
          "label": "Guia de instalação",
          "link": "/pt-BR/dh/10.0.0/DH10-install-pt.pdf"
        },
        {
          "label": "Guia do produto",
          "link": "/pt-BR/dh/10.0.0/DH10-product-pt.pdf"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/l10n/it-IT/ce-claims/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "CustomerEngage Account Management for ClaimCenter",
  "template": "page",
  "class": "threeCards version it-IT l10n",
  "items": [
    {
      "label": "2022.05",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guida all'applicazione",
          "link": "/l10n/pdfs/it-IT/ce-claims/2022.05/it-IT Digital v.2022.05 CE-AM Claims_AppGuide.pdf"
        },
        {
          "label": "Guida all'installazione",
          "link": "/l10n/pdfs/it-IT/ce-claims/2022.05/it-IT Digital v.2022.05 CE-AM Claims InstallGuide.pdf"
        }
      ]
    },
    {
      "label": "11.3",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "Guida all'installazione",
          "link": "/l10n/pdfs/it-IT/ce-claims/11.3/it-CE-Claims-11.3-onprem- InstallGuide.pdf"
        }
      ]
    }
  ],
  "selector": {
    "label": "Seleziona il prodotto",
    "selectedItem": "CustomerEngage Account Management for ClaimCenter",
    "items": [
      {
        "label": "BillingCenter",
        "page": "../bc"
      },
      {
        "label": "ClaimCenter",
        "page": "../cc"
      },
      {
        "label": "Cloud Data Access",
        "page": "../cda"
      },
      {
        "label": "CustomerEngage Account Management",
        "page": "../ce-am"
      },
      {
        "label": "CustomerEngage Quote and Buy",
        "page": "../ce-qb"
      },
      {
        "label": "DataHub",
        "page": "../dh"
      },
      {
        "label": "Guidewire Cloud Console",
        "page": "../gcc"
      },
      {
        "label": "Guidewire Identity Federation Hub",
        "page": "../gwid"
      },
      {
        "label": "InfoCenter",
        "page": "../ic"
      },
      {
        "label": "PolicyCenter",
        "page": "../pc"
      },
      {
        "label": "ProducerEngage",
        "page": "../pe"
      },
      {
        "label": "ProducerEngage for ClaimCenter",
        "page": "../pe-claims"
      },
      {
        "label": "ServiceRepEngage",
        "page": "../sre"
      },
      {
        "label": "VendorEngage",
        "page": "../ve"
      }
    ]
  }
}

=== johnstamps2020/documentation-portal/frontend/pages/globalContent/iplm/hakuba/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "London Market",
  "template": "page",
  "class": "twoColumns",
  "items": [
    {
      "label": "Release Notes",
      "class": "subject releaseNotes",
      "items": [
        {
          "label": "Release Notes",
          "id": "londonrnhakuba"
        }
      ]
    },
    {
      "label": "Developers",
      "class": "subject development",
      "items": [
        {
          "label": "Configuration Guide",
          "id": "londonconfighakuba"
        }
      ]
    },
    {
      "label": "Features and functionality",
      "class": "subject featuresAndFunctionality",
      "items": [
        {
          "label": "ClaimCenter for London Market Application Guide",
          "id": "londonccapphakuba"
        },
        {
          "label": "PolicyCenter for London Market Application Guide",
          "id": "londonpcapphakuba"
        }
      ]
    }
  ]
}

=== johnstamps2020/documentation-portal/frontend/pages/cloudProducts/cortina/policyCenterCloud/linesOfBusiness/businessowners/index.json
{
    "title": "Businessowners Standards Based Template",
    "template": "page.j2",
    "class": "twoColumns",
    "items": [
      {
        "label": "Release Notes",
        "class": "subject releaseNotes",
        "items": [
          {
            "label": "Countrywide Release Notes",
            "id": "lobbopsbtrncortina"
          }
        ]
      },
      {
        "label": "Features and functionality",
        "class": "subject featuresAndFunctionality",
        "items": [
          {
            "label": "Businessowners Standards Based Template Guide",
            "id": "lopbopguidecortina"
          }
        ]
      }
    ]
  }

=== johnstamps2020/documentation-portal/frontend/pages/selfManagedProducts/index.json
{
  "$schema": "/frontend/page-schema.json",
  "title": "Self-managed",
  "template": "page",
  "class": "threeCards self-managed",
  "items": [
    {
      "label": "Core",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "What's New for Self-Managed Implementations",
          "link": "https://www.brainshark.com/1/player/guidewire?pi=zGSzK26rDzeZ1oz0&r3f1=&fb=0"
        },
        {
          "label": "PolicyCenter",
          "page": "pc/10.2.1"
        },
        {
          "label": "ClaimCenter",
          "page": "cc/10.2.1"
        },
        {
          "label": "BillingCenter",
          "page": "bc/10.2.1"
        },
        {
          "label": "InsuranceSuite Configuration Upgrade Tools",
          "id": "isconfigupgradetools440"
        },
        {
          "label": "InsuranceSuite Configuration Upgrade Tools Compatibility",
          "id": "isupgradecompatibility"
        },
        {
          "label": "REST API Client",
          "id": "isrestapiclientguide"
        },
        {
          "label": "REST API Client Release Notes",
          "id": "isrestapiclientrn"
        },
        {
          "label": "Guidewire for Salesforce",
          "page": "gwsf/di/3.4"
        },
        {
          "label": "Global Content",
          "class": "group",
          "items": [
            {
              "label": "France",
              "page": "../globalContent/ipf/2.0"
            },
            {
              "label": "Germany",
              "page": "../globalContent/ipg/latest"
            }
          ]
        }
      ]
    },
    {
      "label": "Analytics",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "DataHub",
          "page": "dh/10.8.0"
        },
        {
          "label": "InfoCenter",
          "page": "ic/10.8.0"
        },
        {
          "label": "DataHub",
          "page": "dh/10.7.0",
          "env": ["prod"]
        },
        {
          "label": "InfoCenter",
          "page": "ic/10.7.0",
          "env": ["prod"]
        }
      ]
    },
    {
      "label": "Digital",
      "class": "categoryCard cardShadow",
      "items": [
        {
          "label": "CustomerEngage Account Management",
          "id": "dxceam1141"
        },
        {
          "label": "CustomerEngage Account Management for ClaimCenter",
          "id": "dxceclaims1141"
        },
        {
          "label": "CustomerEngage Quote and Buy",
          "id": "dxceqb1141"
        },
        {
          "label": "Jutro Design System",
          "page": "../jutroDesignSystem/5.3.1",
          "env": ["dev", "staging", "prod", "int"]
        },
        {
          "label": "ProducerEngage",
          "id": "dxpe1141"
        },
        {
          "label": "ProducerEngage for ClaimCenter",
          "id": "dxpeclaims1141"
        },
        {
          "label": "ServiceRepEngage",
          "id": "dxsre1141"
        },
        {
          "label": "VendorEngage",
          "id": "dxve1141"
        }
      ]
    }
  ],
  "search_filters": {
    "platform": ["Self-managed"]
  }
}
