=== johnstamps2020/documentation-portal/.teamcity/config/config-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://docs.guidewire.com/config.schema.json",
  "title": "Config",
  "description": "A config for the doc-portal",
  "type": "object",
  "properties": {
    "sources": {
      "description": "A list of sources where we can get files for builds",
      "type": "array",
      "items": {
        "$ref": "#/definitions/source"
      }
    },
    "builds": {
      "description": "A list of builds with metadata to run",
      "type": "array",
      "items": {
        "$ref": "#/definitions/build"
      }
    },
    "pages": {
      "description": "A list of landing pages to show on the website",
      "type": "array",
      "items": {
        "$ref": "#/definitions/page"
      }
    },
    "links": {
      "description": "A list of static links with metadata",
      "type": "array",
      "items": {
        "$ref": "#/definitions/link"
      }
    }
  },
  "definitions": {
    "id": {
      "description": "A unique ID",
      "type": "string"
    },
    "title": {
      "description": "A human-readable title, for displaying to humans in various human scenarios. All of us humans know what it is. Right, fellow humans?",
      "type": "string"
    },
    "pageType": {
      "description": "The type of HTML page this build generates. This is useful for crawling.",
      "type": "string",
      "enum": ["oxygenWebhelp", "portal2"]
    },
    "metadata": {
      "description": "Metadata used for classification, search filtering, grouping on landing pages, etc.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "product": {
          "description": "The name of the product",
          "type": "string",
          "examples": ["PolicyCenter", "Jutro", "DataHub"]
        },
        "platform": {
          "description": "The broad category of how we deliver products. Can be Self-managed or Cloud",
          "type": "string",
          "enum": ["Self-managed", "Cloud"]
        },
        "version": {
          "description": "A version number, or a word like 'latest'",
          "type": "string"
        }
      }
    },
    "source": {
      "description": "A source where we can get files from, for example Git, XDocs, etc.",
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "sourceType", "gitUrl"],
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "sourceType": {
          "description": "The type of the source",
          "type": "string",
          "enum": ["git", "xdocs"]
        },
        "gitUrl": {
          "description": "All sources need to be associated with a git repo, so that we can export them for build",
          "type": "string"
        },
        "xdocsPathIds": {
          "description": "A list of pathIds to be exported from XDocs",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "link": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "url", "metadata", "pageType"],
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "title": {
          "$ref": "#/definitions/title"
        },
        "url": {
          "description": "The url of the resource we're linking to. Can be relative to the root, or an absolute URL that starts with https://",
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "pageType": {
          "$ref": "#/definitions/pageType"
        }
      }
    },
    "page": {
      "type": "object",
      "additionalProperties": false,
      "required": ["view", "route"],
      "properties": {
        "view": {
          "description": "The name of the view to use on the server",
          "type": "string"
        },
        "route": {
          "description": "The address on the server, relative to the root",
          "type": "string",
          "examples": ["/", "/self-managed/all-releases", "/audiences"]
        }
      }
    },
    "build": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "title",
        "metadata",
        "buildType",
        "pageType",
        "filter",
        "root",
        "src",
        "url"
      ],
      "properties": {
        "id": {
          "$ref": "#/definitions/id"
        },
        "title": {
          "description": "A human-readable title, for displaying to humans in various human scenarios. All of us humans know what it is. Right, fellow humans?",
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/metadata"
        },
        "buildType": {
          "description": "The build type to apply",
          "type": "string",
          "enum": ["dita"]
        },
        "pageType": {
          "$ref": "#/definitions/pageType"
        },
        "filter": {
          "description": "The name of the ditaval file to use in the build, including the extension",
          "type": "string",
          "examples": [
            "operator.ditaval",
            "IS-BC-Cloud-Draft.ditaval",
            "audience.xml"
          ]
        },
        "root": {
          "description": "The filename of the ditamap to use, including the extension",
          "examples": ["_superbook.ditamap", "flowers.ditamap", "webhelp.xml"]
        },
        "src": {
          "description": "Refers to the ID of an item in the 'sources' array in this config.",
          "type": "string"
        },
        "url": {
          "description": "The URL where the build is going to be available on the site, relative to the root. Do not include the left-most slash",
          "type": "string",
          "examples": ["cloud/in/latest", "self-managed/bc/1003"]
        }
      }
    }
  }
}

=== johnstamps2020/documentation-portal/.teamcity/config/gw-docs-int.json
{
  "$schema": "./config-schema.json",
  "pages": [
    { "view": "home", "route": "/" },
    { "view": "self-managed-latest-dev", "route": "/self-managed-latest" },
    {
      "view": "self-managed-all-releases-dev",
      "route": "/self-managed-all-releases"
    }
  ],
  "links": [
    {
      "id": "selfmanagedbcppypbadq",
      "title": "BillingCenter",
      "url": "self-managed/bc/1003",
      "pageType": "oxygenWebhelp",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "10.0.3"
      }
    },
    {
      "id": "selfmanagedbctnmesrxz",
      "title": "BillingCenter",
      "url": "self-managed/bc/1002",
      "pageType": "oxygenWebhelp",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "10.0.2"
      }
    },
    {
      "id": "selfmanagedbcfdwpzjga",
      "title": "BillingCenter",
      "url": "self-managed/bc/1001",
      "pageType": "oxygenWebhelp",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "10.0.1"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterindexhtmlzrfofjtc",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_10.0.0/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "10.0.0"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterindexhtmlrlwosjzc",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.8/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.8"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterindexhtmlrxkvlypo",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.7/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.7"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterindexhtmluleishgj",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.6/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.6"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterindexhtmlvhqrxxso",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.5/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.5"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocindexhtmlskyxwqbr",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.4/doc/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.4"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocindexhtmluaykxhzw",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.3/doc/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.3"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocindexhtmlzilplqci",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.2/doc/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.2"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocindexhtmlocbqfnfe",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.1/doc/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.1"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocindexhtmloecjqgsa",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_9.0.0/doc/index.html",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "9.0.0"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdoclgknogoq",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.7/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.7"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocrwafpooh",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.6/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.6"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocpqdupbhg",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.5/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.5"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocnqfuedsc",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.4/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.4"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocxubburnq",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.3/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.3"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocdshtuisn",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.2/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.2"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocrlhufvsc",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.1/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.1"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdoculdoiyfk",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_8.0.0/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "8.0.0"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdociazmuaja",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_7.0.8/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "7.0.8"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocfjgzsxug",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_7.0.7/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "7.0.7"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocdgvtlrvo",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_7.0.6/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "7.0.6"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocudtzgidf",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_7.0.5/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "7.0.5"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdocfrfoalhc",
      "title": "BillingCenter",
      "url": "https://portal2.guidewire.com/portal/secure/doc/bc/BillingCenter_7.0.4/doc/",
      "pageType": "portal2",
      "metadata": {
        "platform": "Self-managed",
        "product": "BillingCenter",
        "version": "7.0.4"
      }
    },
    {
      "id": "httpsportalguidewirecomportalsecuredocbcillingenterdochzpelmbs",
      "title": "BillingCenter",
